[package]
name = "m"
version = "0.1.0"
edition = "2024"

[dependencies]
inquire = "0.7.5"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
crossterm = "0.27"